"""initial_schema

Revision ID: 3b772aadc5b9
Revises: 
Create Date: 2026-04-08 15:39:36.658345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b772aadc5b9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dark_sky_sites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('darkness_tier', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('journeys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('literary_locations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('work_title', sa.String(length=255), nullable=False),
    sa.Column('creator', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('naptan_access_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('atco_code', sa.String(length=32), nullable=False),
    sa.Column('naptan_code', sa.String(length=64), nullable=True),
    sa.Column('common_name', sa.String(length=512), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('stop_type', sa.String(length=16), nullable=True),
    sa.Column('locality_name', sa.String(length=255), nullable=True),
    sa.Column('nptg_locality_code', sa.String(length=32), nullable=True),
    sa.Column('administrative_area_code', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('atco_code')
    )
    op.create_table('nptg_localities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nptg_locality_code', sa.String(length=32), nullable=False),
    sa.Column('locality_name', sa.String(length=255), nullable=False),
    sa.Column('parent_locality_name', sa.String(length=255), nullable=True),
    sa.Column('administrative_area_code', sa.String(length=16), nullable=True),
    sa.Column('source_locality_type', sa.String(length=64), nullable=True),
    sa.Column('grid_type', sa.String(length=16), nullable=True),
    sa.Column('easting', sa.Float(), nullable=True),
    sa.Column('northing', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nptg_locality_code')
    )
    op.create_table('journey_stops',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('journey_id', sa.Integer(), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('stop_type', sa.Enum('transit', 'story_poi', 'dark_sky', name='stoptype'), nullable=False),
    sa.Column('literary_location_id', sa.Integer(), nullable=True),
    sa.Column('dark_sky_site_id', sa.Integer(), nullable=True),
    sa.Column('naptan_access_node_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('transport_mode', sa.Enum('walk', 'bicycle', 'bus', 'train', 'car', 'flight', name='transportmode'), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['dark_sky_site_id'], ['dark_sky_sites.id'], ),
    sa.ForeignKeyConstraint(['journey_id'], ['journeys.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['literary_location_id'], ['literary_locations.id'], ),
    sa.ForeignKeyConstraint(['naptan_access_node_id'], ['naptan_access_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journey_stops')
    op.drop_table('nptg_localities')
    op.drop_table('naptan_access_nodes')
    op.drop_table('literary_locations')
    op.drop_table('journeys')
    op.drop_table('dark_sky_sites')
    # ### end Alembic commands ###
