"""add_reference_indexes

Revision ID: d144edbcc207
Revises: 3b772aadc5b9
Create Date: 2026-04-08 15:56:00.990473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd144edbcc207'
down_revision: Union[str, Sequence[str], None] = '3b772aadc5b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_literary_region', 'literary_locations', ['region'], unique=False)
    op.create_index('ix_naptan_admin_area', 'naptan_access_nodes', ['administrative_area_code'], unique=False)
    op.create_index('ix_naptan_stop_type', 'naptan_access_nodes', ['stop_type'], unique=False)
    op.create_index('ix_nptg_admin_area', 'nptg_localities', ['administrative_area_code'], unique=False)
    op.create_index('ix_nptg_locality_name', 'nptg_localities', ['locality_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nptg_locality_name', table_name='nptg_localities')
    op.drop_index('ix_nptg_admin_area', table_name='nptg_localities')
    op.drop_index('ix_naptan_stop_type', table_name='naptan_access_nodes')
    op.drop_index('ix_naptan_admin_area', table_name='naptan_access_nodes')
    op.drop_index('ix_literary_region', table_name='literary_locations')
    # ### end Alembic commands ###
